server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:Usuario
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  application:
    name: usuario-service

      
jwt:
  secret: tokenforjwtsignature
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
  


  
      
