spring:
  datasource:
    url: jdbc:h2:mem:Aluno
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      
jwt:
  secret: tokenforjwtsignature
